### ISSUE TITLE
When setting more than 1 tag, only the last tag in the list is set.

### ISSUE THREAD

**Issue by kostasns** [oracle/oci-compute-jenkins-plugin#10]
Hello,

When setting more than 1 tag, only the last tag in the list is set.

Example:
namespace.tag1=value1
namespace.tag2=value2
namespace.tag3=value3

only namespace.tag3=value3 is set on the instance.

**Comment by AndreyAdnreyev** [comment]
Hi @kostasns ,

Thanks for reporting! Will look at this.

**Comment by AndreyAdnreyev** [comment]
Added to 1.0.12
