### ISSUE TITLE
Shape VM.Standard.E4.Flex is not available in the list of Configure Clouds

### ISSUE THREAD

**Issue by samasc30** [oracle/oci-compute-jenkins-plugin#13]
Shape `VM.Standard.E4.Flex` is now available in most OCI regions, but it is not available in `Shape` dropdown list in Configure Clouds (http://jenkins:8080/configureClouds/)

**Comment by kennedyjf** [comment]
Hi samasc30,

Checking the latest version of the Plugin I can see E4.Flex as an option. 

![image](https://user-images.githubusercontent.com/20243126/118269538-c9f11680-b4b6-11eb-81bb-38ef0c6e3157.png)

What I would suggest is 
1) Check you have the latest version of the Plugin
2) The Image you are using is supported for this Shape. For example if you are using a custom Image built before E4.Flex was available is may not be in the Supported List of Images.

Thanks,
Joe

**Comment by samasc30** [comment]
Thank you for clarification.
I can confirm Jenkins `2.277.4` with Oracle Cloud Infrastructure Compute Plugin `1.0.14` has `VM.Standard.E4.Flex` available on the list for the images supporting this shape.
