### ISSUE TITLE
After build, vm is not destroyed. Plugin's crucial purpose does not work.

### ISSUE THREAD

**Issue by evilvoices** [oracle/oci-compute-jenkins-plugin#20]
The great idea of ​​this plugin is to dynamically create a VM to run builds without wasting machine.
At the end of the Build, the machine remains there forever.

**Comment by rwx42** [comment]
@evilvoices please provide more information about your template configuration. There is the option - "Idle Termination Minutes" which controls termination behaviour. What values is set for it and what is in the jenkins logs?

**Comment by evilvoices** [comment]
> @evilvoices please provide more information about your template configuration. There is the option - "Idle Termination Minutes" which controls termination behaviour. What values is set for it and what is in the jenkins logs?

Good morning, sorry for the delay.

After adjusting the "Idle Termination Minutes" everything started to happen as expected.

But after some time I consistently get the following error while installing Init Script packages:

HTTP ERROR 404 Not Found
URI: /computer/oci-compute-c1e493fc-14a2-4d6d-a9c7-44dcdf11791c/logText/progressiveHtml

STATUS: 404
MESSAGE:

Not Found
SERVLET: Stapler

The plugin after this error destroys the machine and tries again in infinite looping.

After about 30 or 40 attempts, he manages to finish setting up the machine at some point.

I didn't find any coherent information on the subject, just an article about the same error with the AWS plugin but the suggestions for the resolution don't make the slightest sense.

So... I need to make the decision if I try to solve this problem or if I discontinue using the plugin.

The environment is in production and this impasse forces me to change my strategy.

If you have any coherent reference about this problem, I will be happy to act to continue using the plugin that is sensational.

Thanks!

**Comment by rwx42** [comment]
@evilvoices 
It seems that there is some issue with the init script step. There are agents logs when agents are starting. Could you please verify those logs? It could be some timeout issue depending on the init script content. There is the option "Init Script Timeout"  where you can increase timeout.

**Comment by evilvoices** [comment]
Thanks for the answer!

Yes, the Init Script Timeout is set to 1200 seconds.
The Init script runs normally but there is something strange.

The error I mentioned occurs at any point in the script, randomly, but sometimes, for unknown reasons, it fails to install Java.

I'm using ubuntu 22.04 and the command is apt install default-jre which installs openjdk-11. This command sometimes fails and the end of the process says that Java did not install. Without any modifications, sometimes it installs Java, but it gives the mentioned error. I came to suspect that it was the API of the OCI itself or some problem in the OCI repository, because everything worked normally and without any modifications, I started to receive this error. Very rarely is the process 100% successful. It's completely random.

See my Init Script:

#! /bin/bash
sudo apt --purge remove needrestart -y
sudo apt autoremove -y
sudo apt autoclean
sudo apt update && sudo apt upgrade -y
sudo usermod -aG sudo ubuntu
sudo ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
sudo dpkg-reconfigure --frontend noninteractive tzdata
sudo apt install default-jre -y
sudo mkdir -m 0755 -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
cat << EOT >> /home/ubuntu/.ssh/authorized_keys
private-key-1
private-key-2
EOT
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

Thank you for your time.
