### ISSUE TITLE
Sample pipeline code

### ISSUE THREAD

**Issue by luis-lf** [oracle/oci-compute-jenkins-plugin#3]
Hi,

Do you have any pipeline code to test the plugin?

I created the cloud and instance template on Jenkins and now I'm trying to test it out.

Thanks,

**Comment by fkrestan** [comment]
Hi Luis,
we do not provide any special facility for pipelines. You can use labels to target Agents the same way as you would use them with manually provisioned ones. The only significant difference is that the Agents are provisioned on demand. You just have to use the label configured in the Template section of our plugin config (the "any" and "none" agent keywords works as expected too):

```
pipeline {
    agent {
        label 'oci-compute-template-label'
    }

    stages {
        stage('Build') {
            steps {
                sh 'uname -a'
                echo 'Doing something useful'
           }
        }
        stage('Test') {
            steps {
                sh 'uname -a'
                echo 'Doing some other useful thing'
            }
        }
    }
}
```
