### ISSUE TITLE
Connectivity to slave nodes fails

### ISSUE THREAD

**Issue by abannang** [oracle/oci-compute-jenkins-plugin#4]
I am using the OCI plugin to connect slave nodes to Jenkins Master. I am running Jenkins Master on one of the instances on OCI and used the plugin to spin up a slave node and it was failing. I could see the slave instance being launched on the OCI dashboard, but the connectivity between master and slave is not being established. The log on Jenkins console indicates

ERROR: Unexpected error in launching an agent. This is probably a bug in Jenkins
java.io.EOFException: unexpected stream termination
	at hudson.remoting.ChannelBuilder.negotiate(ChannelBuilder.java:409)
	at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:354)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:415)
	at com.oracle.cloud.baremetal.jenkins.ssh.SshComputerLauncher.launch(SshComputerLauncher.java:142)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:288)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I attached the necessary screen shots and stacktrace. I also tried running Jenkins locally on my Mac and using OCI-plugin tried spinning instances on OCI, it still fails with the same error. 

![jenkins dashboard](https://user-images.githubusercontent.com/28656817/39401826-04c731d8-4b04-11e8-8c90-f67ef64d4292.png)
![oci dashboard](https://user-images.githubusercontent.com/28656817/39401827-0a128f20-4b04-11e8-8a6a-269d0038962f.png)
[stacktrace.txt](https://github.com/oracle/oci-compute-jenkins-plugin/files/1958300/stacktrace.txt)
![error log on jenkins console](https://user-images.githubusercontent.com/28656817/39401830-142bbf72-4b04-11e8-95f9-5fd66e98d516.png)
![screen shot of strack trace](https://user-images.githubusercontent.com/28656817/39401833-408800e4-4b04-11e8-9ba3-666aec3f4f43.png)

**Comment by abannang** [comment]
I have Java 8 installed on the Master and it is a VMstandard 1.1 shape with Oracle-Linux-7.5-2018.04.20-0 image

My Jenkins has these plugins installed
Bouncy castle API plugin - 2.16.2
OCI plugin - 1.0.1
SSH credentials plugin - 1.13
SSH slaves plugin - 1.26

The slave instance I am spinning up using OCI plugin template is
VM Standard 1.4 with Oracle-Linux-7.5-2018.04.20-0 image

The slave node does not have Java installed, because it is auto launched by plugin. I tried installing Java on the slave after it’s launch, but that didn’t help.

**Comment by abannang** [comment]
Also, I installed the OCI plugin through Jenkins dashboard and not manually.

**Comment by kennedyjf** [comment]
Hi Abhiram,

Thanks for your reply.

If your Image does not have Java 8 installed it can show an error like this. Note: we have a fix in the next release that will show a clearer error message.

The Images do not have Java installed.

1) In OCI create an Instance, Install Java, Save Image and use this Image in the OCI Template configuration
2) Init Script. You can use the latest OL Images and "sudo install -y java" in the Init Script section of the OCI Template configuration. This will install java at startup.

Please try this and let me know if it works or if you have any questions.

Thanks,
Joe

**Comment by kennedyjf** [comment]
"sudo yum install -y java" in the Init Script section

**Comment by abannang** [comment]
I tried doing that. I used "sudo yum install -y java" in the init script section of the template. This time, the slave node does not even get listed both on the OCI console and also on the Jenkins console.

**Comment by abannang** [comment]
Actually it worked, I forgot to select the instance shape in the template and it did not throw any error. Once I selected the instance shape, it installed java and slave got connected. Thanks for the tip. Closing.

**Comment by kennedyjf** [comment]
Hi Abhi,

Thank you for the update.

Correct it's one AD per Template. It matches the OCI behavior in Oracle Cloud Infrastructure Console.

Also, be picking an AD you can have different selections later in the Template i.e. Subnets.

Thanks,
Joe
