### ISSUE TITLE
Launched instance's connection doesn't go through -  public key authentication failed - but works when explicitly triggering Launch Agent

### ISSUE THREAD

**Issue by bsnareshorc** [oracle/oci-compute-jenkins-plugin#5]
We have a Jenkins server running in OCI. 
Configured an instance template to launch a slave in certain AD of OCI, provided the public key and private key to be used, the connectivity with these keys has been verified.

Upon provisioning a slave via the manage nodes screen, the instance gets launched but the node remains in the offline state, the node log says 

java.io.IOException: Cannot read full block, EOF reached.
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:81)
        ...
        Caused: java.io.IOException: The connection is closed.
	at com.trilead.ssh2.auth.AuthenticationManager.deQueue(AuthenticationManager.java:66)
        ...
        Caused: java.io.IOException: Publickey authentication failed.
	at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:291)

Full log obtained by the logger for com.oracle.cloud.baremetal.jenkins is attached.

When in this offline state, if I navigate to the node in the jenkins page and click on **Launch Agent**, it is able to launch the agent and the slave gets connected.

I was planning to use this plugin to dynamically spin up instances in OCI on demand, and have them terminated while they are offline. But, this problem seems to be causing a blocker.

Is this a known limitation with the OCI plugin? 

The following are the versions of the plugins we are using:

  Oracle Cloud Infrastructure Compute Classic Plugin - 1.0.0
  Oracle Cloud Infrastructure Compute Plugin - 1.0.2

Also, the image that we are using already had JDK8 installed on it, also we have a pre-init script which does the JDK 8 installation.
[oci_plugin_unable_to_connect_to_launchedInstance.txt](https://github.com/oracle/oci-compute-jenkins-plugin/files/2320975/oci_plugin_unable_to_connect_to_launchedInstance.txt)

**Comment by saisantoshi76** [comment]
Is there any workaround for this issue. We are blocked from Jenkins connectivity to these machines.

**Comment by kennedyjf** [comment]
Thanks for your feedback.

Not sure we've seen this issue.

The error seems to indicates an issue that says "Publickey authentication failed."

Which Plugin is used for the config? Please use Oracle Cloud Infrastructure Compute Plugin - 1.0.2 and remove Oracle Cloud Infrastructure Compute Classic Plugin - 1.0.0.

Try this test, to see if its an issue with Plugin or Jenkins connectivity issue:
1) In OCI create an Instance with exact same config as defined in the Template. Same AD, network, image, etc.
2) In Jenkins, create a`New Node to point to this to see if it comes up OK.

**Comment by bsnareshorc** [comment]
I have tried the test that you suggested -
1. Created an instance in OCU using the same config as defined in the template
2. The slave got started when I followed the New Node wizard.

It doesn't seem to be a Jenkins connectivity issue.

**Comment by bsnareshorc** [comment]
Turns out that this is a configuration error. I have set a low SSH connection timeout value (30 secs), increasing it to 120 secs resolved the problem. The plugin was trying to SSH while the instance was still booting up, the exception stack trace somehow convey the real cause.
