### ISSUE TITLE
Launching a windows slave

### ISSUE THREAD

**Issue by IncredibleLou** [oracle/oci-compute-jenkins-plugin#7]
Is it in general possible to launch a windows slave? 

The machine is correctly started and terminated without any errors, but naturally it will not be registered, because no SSH server is installed. 

Has anyone tried it and has an idea what I need to do?

**Comment by kennedyjf** [comment]
Thank you for your feedback.

We tested this and we found that Windows Slaves can work with the Plugin.

Windows Images need to have SSH (i.e. OpenSSH) configured and working and JDK installed. 

If you can SSH to Windows Image, Save the Custom Image and use this in the OCI Plugin Template.

We found that this is inline with how Azure Plugin does it also. 

Please let me know if you have any questions.

**Comment by IncredibleLou** [comment]
Hi. Thanks for the answer. I got it running after a while. 
Only the init-scripts in the template configuration weren't working, But it wasn't that much of a problem.
