### ISSUE TITLE
Feature Request: allow passing network security groups (NSGs) to instance

### ISSUE THREAD

**Issue by jsgarmon** [oracle/oci-compute-jenkins-plugin#8]
I am able to use this plugin to successfully launch an agent in Oracle Cloud. However, Jenkins cannot connect to this agent until I manually log in to the Oracle Console, find the Jenkins instance, and add a network security group to it.

In the OCI API, I can specify NSG at launch time with the `--nsg-ids` flag in the `oci compute instance launch` command, and it would be great if this were an option in the agent template as well. A generic "Additional launch arguments" might be best where we could pass an arbitrary number of arguments to the instance launch command.

**Comment by AndreyAdnreyev** [comment]
Hi @jsgarmon !
Thanks for pointing this out. We will look at this feature!

**Comment by AndreyAdnreyev** [comment]
Added to v1.0.9
