### ISSUE TITLE
Feature Request: Allow to set Tags for Instances

### ISSUE THREAD

**Issue by kostasns** [oracle/oci-compute-jenkins-plugin#9]
Hello,

We track all our billing using tags on the resources, so an option to set a Freeform or Defined tag on the Instances which plugin spins up would be very appreciated.

**Comment by AndreyAdnreyev** [comment]
Hi @kostasns ,
This feature is under development.It will be in the next release. 
Thanks,
Andrey

**Comment by kostasns** [comment]
Great! Thanks for the heads up :)

**Comment by AndreyAdnreyev** [comment]
Done in version 1.0.11
